name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    steps:
      - name: Stop Application Pool
        shell: cmd
        run: '"C:/azagent/A1/_work/_tasks/IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba/0.156.10/node_modules/webdeployment-common-v2/MSDeploy3.6/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="Hello-World",recycleMode="StopAppPool",computerName="202.92.6.94:33",username="administrator",password="qwer1234QWER",AuthType="Basic"'
